version: "3.8"
services:
  db01:
    build:
      context: ./Docker-files/db
    image: deepak199954/vprofiledb
    container_name: db01 
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
  mc01:
    image: memcached
    container_name: mc01 
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    container_name: vpromq01 
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
  app01:
    build:
      context: ./Docker-files/app
    image: deepak199954/vprofileapp
    container_name: app01 
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  web01:
    build:
      context: ./Docker-files/web
    image: deepak199954/vprofileweb
    container_name: web01 
    ports:
      - "80:80"  

volumes:
  vprdbdata: {}
  vproappdata: {}